development:
  adapter: sqlite3
  database: db/Trellito_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/Trellito_test
  host: localhost
  pool: 5
  timeout: 5000
